### ISSUE TITLE
Make command doesn't work

### ISSUE THREAD

**Issue by basco-johnkevin** [etrepum/couchperuser#12]
I'm getting an error when I run the make command:

```
rebar compile
CONFIG ERROR:
Failed to run couch-config --erl-libs-dir
Ensure that couch-config is on the PATH, or set ERL_LIBS appropriately

==> couchperuser (compile)
Compiling src/couchperuser.erl failed:
src/couchperuser.erl:4: can't find include lib "couch/include/couch_db.hrl"
src/couchperuser.erl:22: undefined macro 'LOG_DEBUG/2'
src/couchperuser.erl:6: function init/1 undefined
src/couchperuser.erl:42: record user_ctx undefined
src/couchperuser.erl:48: record changes_args undefined
src/couchperuser.erl:32: function watch_config_changes/0 is unused
ERROR: compile failed while processing /Users/johnkevinmbasco/Library/Application Support/CouchDB/var/lib/couchdb/plugins/couchperuser: rebar_abort
make: *** [compile] Error 1
```

I'm using CouchDB 1.6.1 and I installed it using the installer for OSX.

I already researched for a solution but unfortunately I can't find one :/

I think couch-config command is not available for newer versions for CouchDB?

**Comment by etrepum** [comment]
Perhaps it's just not on your PATH.

**Comment by basco-johnkevin** [comment]
@etrepum Ah, my bad. You're correct. I now added it on my PATH

```
echo $PATH
/usr/local/heroku/bin:/Users/johnkevinmbasco/go/bin:/Users/johnkevinmbasco/.rbenv/shims:/Users/johnkevinmbasco/Development/adt-bundle-mac-x86_64-20140702/sdk/tools/:/Users/johnkevinmbasco/Development/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/johnkevinmbasco/.composer/vendor/bin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/johnkevinmbasco/.rvm/bin:/usr/local/opt/go/libexec/bin:/Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin
```

Unfortunately, it still doesn't work. Im still getting the exact same error I posted above. Any ideas what's wrong?

**Comment by etrepum** [comment]
It looks like the CouchDB installer for Mac is broken, perhaps you should file a bug with them. The `couch-config` that they ship does not report the correct path names. It has hardcoded names from homebrew. You might have better luck setting ERL_LIBS directly. Something like this might work:

```
ERL_LIBS=/Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/lib/couchdb/erlang/lib make
```

**Comment by basco-johnkevin** [comment]
@etrepum It worked! Thanks a lot. Spent hours debugging what's the problem. That explains why when I run `couch-config --erl-libs-dir` the output is `/usr/local/Cellar/couchdb/1.6.1/lib/couchdb/erlang/lib`, but when I cd to that directory, it doesn't exist. Thanks again! :)

**Comment by etrepum** [comment]
Yep. It takes a bit of extra effort to make stuff relocatable (such that you can rename or move an app around on the filesystem and it still works), and it looks like they missed couch-config.
