### ISSUE TITLE
open_revs reponse

### ISSUE THREAD

**Issue by svnlto** [etrepum/couchperuser#14]
I've recently ran into an issue where I'm trying to sync docs out of a userdb with pouchdb. the call below should return with an array containing docs. But instead it just returns the doc itself (this has previously worked - pre couchperuser security fix i believe).

```bash
curl 'http://localhost:8888/data/userdb-622e706965636b40782d696f6e2e6465/7654039ff1fae5d9280e8b2063018bf0?revs=true&open_revs=\[%221-364414175717df854da6e985d1bef0a3%22\]&attachments=true&_nonce=1424782876421' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,de;q=0.6' -H 'x-header: value' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2313.0 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: http://localhost:8888/' -H 'x-token: sometoken' -H 'Connection: keep-alive' --compressed
```
and the reponse doc:

```js
{"_id":"7654039ff1fae5d9280e8b2063018bf0","_rev":"1-364414175717df854da6e985d1bef0a3","id":"someId","gender":"","firstname":"name","lastname":"name","photo":"url","type":"contact","emails":[],"color":"green","isFavourite":false}
```

**Comment by nolanlawson** [comment]
This might be a bug in PouchDB, now that I think about it a bit more. Apparently vanilla CouchDB also doesn't respond with an array when you do `open_revs=["1-x"]`.

**Comment by etrepum** [comment]
couchperuser doesn't get anywhere near these parts of CouchDB, I'm afraid you're barking up the wrong tree here.

**Comment by svnlto** [comment]
yeah, been told so after I've opened this. thanks for responding tho.

On Tuesday, February 24, 2015, Bob Ippolito <notifications@github.com>
wrote:

> couchperuser doesn't get anywhere near these parts of CouchDB, I'm afraid
> you're barking up the wrong tree here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/etrepum/couchperuser/issues/14#issuecomment-75816018>.
>


-- 
The paper industry is in trouble.
Please print three copies of this email.

Twitter: http://twitter.com/svenlito
Github: https://github.com/svnlto

UK Mobile: +44 79 287 32020
DE Mobile: +49 15 785944551
