### ISSUE TITLE
Move couchperuser to Apache CouchDB

### ISSUE THREAD

**Issue by KlausTrainer** [etrepum/couchperuser#15]
Hi @etrepum,

I'm a committer to Apache CouchDB, and I'm writing you in behalf of the project.

You noted [here](https://issues.apache.org/jira/browse/COUCHDB-2191?focusedCommentId=14329444&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14329444) that you would be willing to donate couchperuser to the Apache CouchDB project.

By holding an accordant [vote](http://mail-archives.apache.org/mod_mbox/couchdb-dev/201503.mbox/%3CCAJ1bcfFJfP%3Dv3VLsZJNDobAv7gNgP82S%3DXeEgU2rO50tahNDBg%40mail.gmail.com%3E), the Apache CouchDB project recently decided to accept the couchperuser codebase in its current state (i.e., commit 16bd1f92b94d87e8f69a09988674c8be72652097).

For the final inclusion of couchperuser into Apache CouchDB, we need you to sign the CLA found [here](http://www.apache.org/licenses/icla.txt), and then send it to [secretary@apache.org](mailto:secretary@apache.org).

Thanks,
Klaus

**Comment by etrepum** [comment]
Thanks Klaus! I've just emailed the CLA.

**Comment by KlausTrainer** [comment]
Thank you :)
