### ISSUE TITLE
How to create an custom attribute in user profile after Db created

### ISSUE THREAD

**Issue by raymatos** [etrepum/couchperuser#16]
Hi,

I was trying to modified this to also do the following.

After user DB is created, create an attribute named Databases in the _user DB with a value of the name of the DB that was created for the user.  

here what i have so far, FYI i dont know erlang

basically i'm trying to get the doc from _users and add a attribute name "database" with a value of User_Db.

```
ensure_user_profile(User) ->
    io:format("\n\nensuring user db\n\n"),
    erlang:display(User),
    io:format("\n"),
    User_Db = user_db_name(User),
    erlang:display(User_Db),
    io:format("\nDB NAME => "),
    Db_Name = ?l2b(couch_config:get("couch_httpd_auth", "authentication_db", "_users")),
    erlang:display(Db_Name),
    Options = [],
    case couch_db:open(Db_Name, Options) of
      Ok={ok, Db} ->
        case couch_db:open_doc(Db, "org.couchdb.user:ray") of
          Ok={ok, Doc2} ->
            erlang:display(Doc2),
            Ok;
          _Err ->
            erlang:display(Db),
            io:format("Could not access doc")
        end,
        Ok;
      _Err ->
        io:format("Something went wong")
    end.

```

**Comment by etrepum** [comment]
This seems like a good question to ask the CouchDB developers, unfortunately I haven't used CouchDB in a long while and I don't have the time or current experience to help you with this.
