### ISSUE TITLE
Unable to find the Plugins Directory

### ISSUE THREAD

**Issue by muraliR** [etrepum/couchperuser#17]
There is no plugin directory at /usr/couchdb and also /usr/couchdb is permission denied.

**Comment by webnoob** [comment]
I had the same issue, change your command to use

`sudo mkdir path/to/couchdb/plugins`

**Comment by bshikhar13** [comment]
Hi @webnoob I can't find the path to couchdb in my Redhat machine.

**Comment by etrepum** [comment]
This is a question about couchdb and is not relevant to this plugin in particular.
