### ISSUE TITLE
Suggest users use couch_peruser, which is built-in to CouchDB 2.0

### ISSUE THREAD

**Issue by jacksonrayhamilton** [etrepum/couchperuser#18]
Since https://github.com/etrepum/couchperuser/issues/15, it appears CouchDB 2.0 now includes `couch_peruser`. It can be enabled like this:

```ini
[couch_peruser]
enable = true
```

Would you consider mentioning this in the README?

**Comment by jacksonrayhamilton** [comment]
Although, we may want to wait on that, since apparently `couch_peruser` is also broken right now: https://issues.apache.org/jira/browse/COUCHDB-3246

**Comment by etrepum** [comment]
Happy to accept a PR that makes any relevant updates when the time is right. I'm not actively using or maintaining this myself.
