### ISSUE TITLE
All created users can read/write from/to every db

### ISSUE THREAD

**Issue by Mischosch** [etrepum/couchperuser#8]
Hi there,

I tried the couchperuser plugin with CouchDB 1.6.1. 

The plugin seems to run fine, as a new database in fromat `userdb-hex` gets created for every user I add through the `_users` db.

After creation of 2 testusers with result of 2 related dbs I tried to read/write to that dbs. Got no error/alert. Tried it with pouchdb and a couchdb php client. 

Whatcould I do to debug that more in detail?

regards

Mischosch

**Comment by MindWire** [comment]
I cannot get this working on Debian (couchdb hosted in Google Cloud via Bitnami). See my StackOverflow Question [here](http://stackoverflow.com/questions/42280861/how-to-install-couchperuser-on-debian).

**Comment by etrepum** [comment]
I'm not able to help you with this, but you may want to ask on the usual channels for CouchDB and/or Bitnami questions. From what I understand, CouchDB is bringing this functionality into the core, so you may not need a plugin anymore, but I'm not sure what the status of that is.

**Comment by MindWire** [comment]
Thank you for replying Etrepum. I'll check it out.
